#!/bin/sh                                                                                       

PID="org.daemon.de.netstat"
SID="org.daemon.de.netstatd"
EXE="netstatd"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Install the upstart script
rm -f /etc/event.d/${SID} /var/palm/event.d/${SID}
if [ -d /var/palm/event.d ] ; then
  cp $APPS/usr/palm/applications/${PID}/upstart/${SID} /var/palm/event.d/${SID}
else
  cp $APPS/usr/palm/applications/${PID}/upstart/${SID} /etc/event.d/${SID}
fi

# Stop any existing service
/sbin/stop ${SID} || true

# Make sure it's dead
sleep 2
killall -9 ${EXE} || true

# Install the daemon script
mkdir -p /var/usr/sbin/
rm -f /var/usr/sbin/${EXE}
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${EXE} /var/usr/sbin/${EXE}

# Start the service
/sbin/start ${SID}

# Check the upstart script is installed
[ -f /var/palm/event.d/${SID} ] || [ -f /etc/event.d/${SID} ] || exit 1

exit 0
