#!/bin/sh

PID="org.daemon.de.netstat"
SID="org.daemon.de.netstatd"
EXE="netstatd"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service if running
/sbin/stop ${SID} || true

# Make sure it's dead
sleep 2
killall -9 ${EXE} || true

# Remove the upstart script
rm -f /etc/event.d/${SID} /var/palm/event.d/${SID}

# Remove the daemon script
rm -f /var/usr/sbin/${EXE}

exit 0
